### ISSUE TITLE
无法下载完

### ISSUE THREAD

**Issue by p520504** [HeLiangHIT/douyin_downloader#4]
差不多下载40个退出，过一会儿运行接着下（已下载跳过）。

这part可以理解

但是我看了这id有120个作品，但是下到94个作品后就再也没有解析了

**Comment by HeLiangHIT** [comment]
提示什么错误呢？请截图或者复制错误内容～

**Comment by 1441916133** [comment]
我直接使用win下的版本，单文件，我实在不知道怎么能找到错误日志，但是报错的时候实在是太快了，就闪退了。压根看不清。
我用python运行下py，结果还不如直接运行exe的，提示如下。
====== RESTART: F:\douyin_downloader-release1.0.4\douyin_downloader.py ======
Traceback (most recent call last):
  File "F:\douyin_downloader-release1.0.4\douyin_downloader.py", line 20, in <module>
    from douyin_tool import *
  File "F:\douyin_downloader-release1.0.4\douyin_tool.py", line 7, in <module>
    from util import *
  File "F:\douyin_downloader-release1.0.4\util.py", line 12, in <module>
    import trio, asks, logging, json, time, os, arrow, socket, random
ModuleNotFoundError: No module named 'trio'
>>>

**Comment by 1441916133** [comment]
我直接使用win下的版本，单文件，我实在不知道怎么能找到错误日志，但是报错的时候实在是太快了，就闪退了。压根看不清。
我用python运行下py，结果还不如直接运行exe的，提示如下。
====== RESTART: F:\douyin_downloader-release1.0.4\douyin_downloader.py ======
Traceback (most recent call last):
  File "F:\douyin_downloader-release1.0.4\douyin_downloader.py", line 20, in <module>
    from douyin_tool import *
  File "F:\douyin_downloader-release1.0.4\douyin_tool.py", line 7, in <module>
    from util import *
  File "F:\douyin_downloader-release1.0.4\util.py", line 12, in <module>
    import trio, asks, logging, json, time, os, arrow, socket, random
ModuleNotFoundError: No module named 'trio'
>>>

**Comment by 1441916133** [comment]
我直接使用win下的版本，单文件，我实在不知道怎么能找到错误日志，但是报错的时候实在是太快了，就闪退了。压根看不清。
我用python运行下py，结果还不如直接运行exe的，提示如下。
====== RESTART: F:\douyin_downloader-release1.0.4\douyin_downloader.py ======
Traceback (most recent call last):
  File "F:\douyin_downloader-release1.0.4\douyin_downloader.py", line 20, in <module>
    from douyin_tool import *
  File "F:\douyin_downloader-release1.0.4\douyin_tool.py", line 7, in <module>
    from util import *
  File "F:\douyin_downloader-release1.0.4\util.py", line 12, in <module>
    import trio, asks, logging, json, time, os, arrow, socket, random
ModuleNotFoundError: No module named 'trio'
>>>

**Comment by 1441916133** [comment]
我直接使用win下的版本，单文件，我实在不知道怎么能找到错误日志，但是报错的时候实在是太快了，就闪退了。压根看不清。
我用python运行下py，结果还不如直接运行exe的，提示如下。
====== RESTART: F:\douyin_downloader-release1.0.4\douyin_downloader.py ======
Traceback (most recent call last):
  File "F:\douyin_downloader-release1.0.4\douyin_downloader.py", line 20, in <module>
    from douyin_tool import *
  File "F:\douyin_downloader-release1.0.4\douyin_tool.py", line 7, in <module>
    from util import *
  File "F:\douyin_downloader-release1.0.4\util.py", line 12, in <module>
    import trio, asks, logging, json, time, os, arrow, socket, random
ModuleNotFoundError: No module named 'trio'
>>>

**Comment by HeLiangHIT** [comment]
直接运行py需要安装依赖的： `pip install douyin_downloader`

**Comment by 1441916133** [comment]
安装之后是：====== RESTART: F:\douyin_downloader-release1.0.4\douyin_downloader.py ======
Traceback (most recent call last):
  File "F:\douyin_downloader-release1.0.4\douyin_downloader.py", line 21, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'
>>> 
感觉，这个不能运行无所谓。就是exe打包好的闪退怎么解决。也没有日志，是属于能运行但是下不全就自己退出了。哟第一次下载四十多，第二次下载一百多，第三次，第四次的时候，就一直在检验本地已经下载的，然后随之闪退了。
这个怎么看到错误信息，这个是我所想要问的问题。毕竟没有错误日志没办法排查嘛。

**Comment by HeLiangHIT** [comment]
可以 win + R ，然后  cd  到对应exe文件目录，然后使用在cmd下输入exe名字运行 exe 文件，就不会退了~可以看到日志。

**Comment by 1441916133** [comment]
首先很感谢您那么耐心的告知我操作方法，冬至到了，然后开始给你挖坑。
Traceback (most recent call last):
  File "douyin_downloader\douyin_downloader.py", line 116, in <module>
  File "douyin_downloader\douyin_downloader.py", line 111, in cmd_run
  File "site-packages\trio\_core\_run.py", line 1337, in run
  File "douyin_downloader\douyin_downloader.py", line 95, in main
  File "douyin_downloader\douyin_downloader.py", line 66, in crawler_user_video
  File "site-packages\trio\_core\_run.py", line 397, in __aexit__
  File "douyin_downloader\douyin_downloader.py", line 43, in download_videos
  File "douyin_downloader\util.py", line 237, in save_file
  File "site-packages\trio\_file_io.py", line 170, in open_file
  File "site-packages\trio\_threads.py", line 400, in run_sync_in_worker_thread
  File "site-packages\trio\_core\_traps.py", line 165, in wait_task_rescheduled
  File "site-packages\outcome\_sync.py", line 111, in unwrap
  File "site-packages\trio\_threads.py", line 362, in do_release_then_return_res
ult
  File "site-packages\outcome\_sync.py", line 111, in unwrap
OSError: [Errno 22] Invalid argument: 'F:\\Tik Tok\\97553783068\\favorite\\"阿敏
啊_62044195126_我能.mp4'
[1732] Failed to execute script douyin_downloader

**Comment by 1441916133** [comment]
你的猜测是错误的。
当前下载了700多个视频里面都是按照这个文件夹命名的。并且我修改完之后和之前一样。报错方式也没有什么的不同。
 File "site-packages\outcome\_sync.py", line 111, in unwrap
OSError: [Errno 22] Invalid argument: 'F:\\TikTok\\97553783068\\favorite\\"阿敏
啊_62044195126_我能.mp4'
[1916] Failed to execute script douyin_downloader
我现在要去找那个有毒的视频，揪出来取消点赞。今天找了一次，没成功。我再试试去。

**Comment by HeLiangHIT** [comment]
这个问题貌似涉及到知识盲区了，非官方的异步库果然有一些诡异的bug，这个坑先留着吧～我遇到了再详细分析下😄😄😄，我到 trio 反馈一下看看有没有答复

**Comment by 1441916133** [comment]
我到个人主页页面里边，发现一个很有意思东西。
就是你往下滑，划着划着，他就会发现就没了。然后鼠标在页面里面点击一下，然后又继续加载。然后又可以继续往下滑滑滑。
如果不再页面点击一下就不往下加载，不知道这个对爬取视频有没有影响。

**Comment by 1441916133** [comment]
我根据命名方式尝试找了下报错的那个视频，结果…没有这个抖音号，属于不存在的。根据昵称搜索，一大堆人，也找不到原视频，也找不到视频归属于哪个人。
那么问题来了，下载不下来，他为啥不会跳过去，而是到这里崩溃了。啊哈。

**Comment by HeLiangHIT** [comment]
这个我没遇到过，所以没有跳过去啊～哈哈。我抽空修复一下吧～

**Comment by HeLiangHIT** [comment]
https://github.com/HeLiangHIT/douyin_downloader/releases/download/release1.0.4/douyin_downloader.exe

将就这个版本修复了一下，你用这个版本试试吧~

**Comment by HeLiangHIT** [comment]
我发现是因为windows不支持双引号作为文件名...这个约束倒是忘记了，真是疏忽了...之前脑子一定是被驴踢了居然没想到这个。
